name: Go

on:
  push:
    branches: [ master, develop, 'feature/**' ]
  pull_request:
    branches: [ master, develop, 'feature/**' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        skip-pkg-cache: true
        skip-build-cache: true
